task4/Models/Department.cs
using System;
using System.Collections.Generic;

namespace task4.Models;

public partial class Department
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Location { get; set; }

    public int? ManagerId { get; set; }

    public DateOnly? EstablishedDate { get; set; }
}

task4/Models/ErrorViewModel.cs
namespace task4.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

task4/Models/MyDbContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace task4.Models;

public partial class MyDbContext : DbContext
{
    public MyDbContext()
    {
    }

    public MyDbContext(DbContextOptions<MyDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Server=DESKTOP-057PR2N;Database=Orange;Trusted_Connection=True;TrustServerCertificate=True;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Departme__3214EC2790042918");

            entity.ToTable("Department");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.EstablishedDate).HasColumnName("established_date");
            entity.Property(e => e.Location)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("location");
            entity.Property(e => e.ManagerId).HasColumnName("manager_id");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("name");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC27F10D9416");

            entity.HasIndex(e => e.Email, "UQ__Users__A9D10534DB3A2AD9").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Name).HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

task4/Models/User.cs
using System;
using System.Collections.Generic;

namespace task4.Models;

public partial class User
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Email { get; set; }
}

task4/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace task.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult UsersList()
        {
            return View();
        }
    }
}

task4/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using task4.Models;

namespace task4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            string Username = HttpContext.Session.GetString("UserName");
            ViewData["UserName"] = Username;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

task4/Controllers/UserController.cs
using System.Runtime.Intrinsics.Arm;
using System.Xml.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;

namespace task4.Controllers
{
    public class UserController : Controller
    {
        

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Logout()
        {
            if (HttpContext.Session.GetString("Email") == "Admin@gmail.com")
            {
                HttpContext.Session.Clear();
                return RedirectToAction("Index", "Home");
            }
            string username = HttpContext.Session.GetString("UserName");
            CookieOptions obj = new CookieOptions();
            obj.Expires = DateTime.Now.AddDays(7);
            Response.Cookies.Append("Username", username, obj);
            HttpContext.Session.Clear();
            return RedirectToAction("Index","Home");
        }

        [HttpPost]
        public IActionResult HandelRegister()
        {
            string name = Request.Form["name"];
            string email = Request.Form["email"];
            string pass = Request.Form["password"];
            string repeat = Request.Form["repeatPassword"];

            if (pass == repeat)
            {
                HttpContext.Session.SetString("UserName", name);
                HttpContext.Session.SetString("UserEmail", email);
                HttpContext.Session.SetString("UserPassword", pass);
                return RedirectToAction("Login");
                
            }
            else
            {
                TempData["alert"] = "password not match ";
                return RedirectToAction("Register");
            }
        }

        public IActionResult HandelLogin()
        {
            string email = Request.Form["email"];
            string pass = Request.Form["password"];
            string Remember = Request.Form["Remember"];

            string storedEmail = HttpContext.Session.GetString("UserEmail");
            string storedPassword = HttpContext.Session.GetString("UserPassword");

            string storedEmailCookies = HttpContext.Request.Cookies["Email"];
            string storedPasswordCookies = HttpContext.Request.Cookies["Password"];
            if (pass == "123" && email == "Admin@gmail.com")
            {
                HttpContext.Session.SetString("UserEmail", email);
                HttpContext.Session.SetString("UserPassword", pass);
                return RedirectToAction("Index", "Home");
            }

            if ((pass == storedPassword && email == storedEmail) || (pass== storedPasswordCookies && email == storedEmailCookies))
            {
                if (Remember != null)
                {
                    CookieOptions obj = new CookieOptions();
                    obj.Expires = DateTime.Now.AddDays(7);
                    //store
                    
                    Response.Cookies.Append("Email", email, obj);
                    Response.Cookies.Append("Password", pass, obj);

                }
                if(storedEmail == null)
                {
                    HttpContext.Session.SetString("UserName", HttpContext.Request.Cookies["Username"]);
                    HttpContext.Session.SetString("UserEmail", email);
                    HttpContext.Session.SetString("UserPassword", pass);
                }

                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["alert"] = "password not match ";
                return RedirectToAction("Register");
            }
        }
        public IActionResult Register()
        {
            
            return View();
        }

        public IActionResult Profile()
        {
            
            return View();
        }

        public IActionResult EditProfile()
        {

            return View();
        }

        public IActionResult saveData()
        {
            
            string address = Request.Form["Address"];
            string phone = Request.Form["Phone"];


            HttpContext.Session.SetString("UserAddress", address);
            HttpContext.Session.SetString("UserPhone", phone);
            return RedirectToAction("Profile");
        }

    }
}

task4/Views/Admin/UsersList.cshtml
@{

    // Dynamically loading users (NO CONTROLLER)
    var users = new[] {
        new { Username = "Abdallah", Age = 28, Email = "Abdallah@gmail.com" },
        new { Username = "Sura", Age = 29, Email = "sura@gmail.com" },
        new { Username = "Salah", Age = 30, Email = "salah@gmail.com" }
    };
}

<h2>Users List</h2>
<table class="table table-bordered">
    <thead>
        <tr><th>Username</th><th>Age</th><th>Email</th></tr>
    </thead>
    <tbody>
        @foreach (var user in users)
        {
            <tr>
                <td>@user.Username</td>
                <td>@user.Age</td>
                <td>@user.Email</td>
            </tr>
        }
    </tbody>
</table>

task4/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome,  @Context.Session.GetString("UserName")</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

task4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - task4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/task4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">task4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        @if (Context.Session.GetString("UserEmail") == null )
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                            </li>
                        }
                        else{
                            @if (Context.Session.GetString("UserEmail") == "Admin@gmail.com"){
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="UsersList">Admin</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                                </li>
                            }
                            else{
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Profile">Profile</a>
						        </li>

						        <li class="nav-item">
							        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
						        </li>
                            }
                            
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - task4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>